name: Metrics

on:
  schedule: [{cron: "0 0 * * 1"}] # weekly updates
  workflow_dispatch: # manual update
  push: # when workflow file changes
    paths:
      - .github/workflows/metrics.yml

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Base
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: America/Detroit
          base: header, activity, community, metadata
          base_indepth: yes
          repositories: 200
          user: samarth8392
      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          user: samarth8392
          commits_authoring: Samarth Mathur, samarth8392, samarth8392@users.noreply.github.com, samarth.mathur@nih.gov, samarth8392@gmail.com
          plugin_languages: yes # languages
          plugin_languages_categories: programming
          plugin_languages_recent_categories: programming
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_other: no
          plugin_languages_ignored: html, css, scss, lua, Jupyter Notebook, JavaScript, TeX, PostScript, Apex
          plugin_languages_analysis_timeout: 60
          plugin_languages_details: bytes-size, percentage
          plugin_languages_aliases: RenderScript:Rust, rebol:R, GLSL:JavaScript
          #plugin_languages_threshold: 2%
      - name: Comment reactions
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.reactions.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_reactions: yes
          plugin_reactions_limit: 100
          plugin_reactions_details: percentage
      - name: Compact display
        uses: lowlighter/metrics@latest
        with:  
          filename: metrics.plugin.achievements.compact.svg  
          token: ${{ secrets.METRICS_TOKEN }}  
          base: ""  
          plugin_achievements: yes  
          plugin_achievements_only: polyglot, stargazer, sponsor, deployer, member, maintainer, developer,    scripter, packager, explorer, infographile, manager  
          plugin_achievements_display: compact  
          plugin_achievements_threshold: X
